# Generated by Django 5.1.3 on 2024-12-02 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_ui', '0002_inventory_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playbook',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.AddField(
            model_name='playbook',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playbook',
            name='last_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
