# Generated by Django 5.1.3 on 2024-12-03 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_ui', '0004_remove_job_created_at_remove_job_inventory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='ansible_ui.inventory'),
        ),
    ]
