# Generated by Django 5.1.3 on 2024-12-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_ui', '0008_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
